### ISSUE TITLE
Branch filter is not mentioned on the documentation

### ISSUE THREAD

**Issue by huribeir** [awsdocs/aws-codebuild-user-guide#1]
The functionality of specifying a Branch filter for GitHub/GHE does not appear to be present in the documentation. It would be nice to have that functionality references there, eventually with some examples.

**Comment by markiver** [comment]
Thank you for the feedback. This is new functionality released in the past couple weeks. It's now reflected in the documentation here:

* In the API - 
   -- When creating a project: https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateWebhook.html
   -- When changing a project: https://docs.aws.amazon.com/codebuild/latest/APIReference/API_UpdateWebhook.html

* In the User Guide -
   -- When creating a project: https://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-console (look in the table in step 5 for how to specify a branch filter)
   -- When updating a project: https://docs.aws.amazon.com/codebuild/latest/userguide/change-project.html#change-project-console (look for the same table with the same information as in the above page)

Note that the table in the above two pages do not translate to mark-down well, so the *.md versions of these two files in this GitHub repository refer you to the html User Guilde pages.

Thank you again for the feedback. Customers who take the time to provide requests and feedback, like you, help us keep our documentation as current and helpful as possible.

Kind regards,

Mark

**Comment by sluipmoord** [comment]
Hello,

Is there a way to add a branch filter with a CloudFormation stack

The current docs for triggers does not metion anything: [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html)
