### ISSUE TITLE
Wrong braces for AWS_REGION in hello world example

### ISSUE THREAD

**Issue by TheWinged7** [awsdocs/aws-codebuild-user-guide#10]
The [Build Specification Reference for AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-name-storage) document uses the wrong braces `()` for the AWS_REGION env variable insetad of `{}`

**Current:**
```version: 0.2         
phases:
  build:
    commands:
      - rspec HelloWorld_spec.rb
artifacts:
  files:
    - '**/*'
  name: myname-$(AWS_REGION) 
```

**Corrected:**
```version: 0.2         
phases:
  build:
    commands:
      - rspec HelloWorld_spec.rb
artifacts:
  files:
    - '**/*'
  name: myname-${AWS_REGION)} 
```

**Comment by markiver** [comment]
Hello,

Thank you for your feedback, and my apologies for the delayed response. I consulted with CodeBuild engineers and we decided to update the text above by simply removing the parentheses, so it looks like this:

name: myname-$AWS_REGION

I apologize for any inconvenience and lost time this caused you.

We sincerely appreciate the time you took to let us know about this. It's customers like you who help us keep our documentation as accurate and current as possible.

Thank you again,

Mark
