### ISSUE TITLE
Documentation indicates branch filter support BitBucket, but it's not there

### ISSUE THREAD

**Issue by HakanL** [awsdocs/aws-codebuild-user-guide#20]
The page on https://docs.aws.amazon.com/codebuild/latest/userguide/change-project.html#change-project-cli indicated that BitBucket has support for branch filter, but it's not exposed in the Console, and when setting it via CLI doesn't seem make a difference, everything is still built.

**Comment by markiver** [comment]
Hello,

The branch filter option is deprecated and replaced by webhook filter groups. Please see this troubleshooting topic for details: 

- https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-webhook-filter.

I apologize for frustration this caused you.

Thank you for taking the time to bring this up, and I hope the troubleshooting topic is helpful.

Kind regards,

Mark
