### ISSUE TITLE
Repo doesn't match live docs

### ISSUE THREAD

**Issue by adamchainz** [awsdocs/aws-codebuild-user-guide#3]
https://docs.aws.amazon.com/codebuild/latest/userguide/monitoring-builds.html is up but has no corresponding file in this repo

I came here to fix a typo on that page: "infomration"

**Comment by markiver** [comment]
Hi Adam,

Thank you for your feedback about both the misspelling and the missing documentation in the GitHub repository. Both should now be fixed (the fix in the HTML User Guide may take a short while to propagate to the live site, but rest assured the correction is in place).

Thank you again. It's feedback like yours that helps us keep our documentation as current and useful as possible.

Mark
