### ISSUE TITLE
'list-shared-project' command not found

### ISSUE THREAD

**Issue by pahud** [awsdocs/aws-codebuild-user-guide#50]
https://github.com/awsdocs/aws-codebuild-user-guide/blob/master/doc_source/project-sharing.md#identifying-a-shared-project

<img width="962" alt="圖片" src="https://user-images.githubusercontent.com/278432/70843029-6ba9a980-1e66-11ea-8c27-7e656c150ebf.png">

<img width="1349" alt="圖片" src="https://user-images.githubusercontent.com/278432/70843041-8714b480-1e66-11ea-9c47-aa3174ffca5e.png">

**Comment by markiver** [comment]
Hello,

Thank you for taking the time to point out this incorrect link. I will update the documentation shortly. The correct link is:

https://docs.aws.amazon.com/cli/latest/reference/codebuild/list-shared-projects.html

Thank you again for taking the time to let us know about this. It's customers like you who help us keep our documentation as current, accurate, and useful as possible.

Kind regards,

Mark
