### ISSUE TITLE
Sample for specifying multiple versions of the same runtime in CodeBuild

### ISSUE THREAD

**Issue by trivikr** [awsdocs/aws-codebuild-user-guide#57]
**Is your feature request related to a problem? Please describe.**
* I couldn't find sample for running CodeBuild in multiple versions of the same runtime
  * Example to specify two runtime versions is given here https://docs.aws.amazon.com/codebuild/latest/userguide/sample-runtime-versions.html#sample-runtime-two-major-version-runtimes
* In TravisCI, the multiple versions of the same runtime (say Node.js) can be specified under `node_js`:
  * [Example code](https://github.com/aws/aws-sdk-js/blob/9c4d537fb77928bc0f4406cc121431f857a443db/.travis.yml#L4-L13)
  * [Documentation](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions)
* As explained in https://github.com/aws/aws-sdk-js/pull/3150#issuecomment-599785551, if multiple versions of the same runtime is specified in CodeBuild - the last specified version is used

**Describe the solution you'd like**
Need sample for specifying multiple versions of the same runtime in CodeBuild, if the support exists

**Describe alternatives you've considered**
Continue using TravisCI for running on multiple versions of same runtime and CodeBuild for latest LTS version of the runtime

**Comment by markiver** [comment]
Hi Trivikram,

Thank you for taking the time to create an issue for our CodeBuild documentation. I created a backlog ticket for our documentation to add this sample.

Kind regards,

Mark
