### ISSUE TITLE
Supporting XCode/Android Studio builds

### ISSUE THREAD

**Issue by tirthaguha** [awsdocs/aws-codebuild-user-guide#58]
Does AWS CodeBuild have this in their roadmap?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
