### ISSUE TITLE
[Bug?] CodeBuild EventBridge Notification is coming different than referred in docs

### ISSUE THREAD

**Issue by dpolicastro** [awsdocs/aws-codebuild-user-guide#60]
I subscribed a lambda function to EventBridge CodeBuild Events, but when I log it to CloudWatch looks like some fields are coming with a different format from [the docs](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-build-notifications.html), for example, every field that contains two colons are coming with a single colon and a space, like this: 

**Expected:** 
- build-id: `"arn:aws:codebuild:us-east-1::<Account>:build/node-http-server-example-codebuild-build:af8ff896-6f56-4bea-a7ee-f1b1f446eda8"`
- source.location `"https://github.com/(...).git"`

**Received:** 
- build-id: `"arn:aws:codebuild:us-east-1: <Account>:build/node-http-server-example-codebuild-build:af8ff896-6f56-4bea-a7ee-f1b1f446eda8"`
- source.location `"https: //github.com/(...).git"`

**Comment by strohm-a** [comment]
Thank you for reporting this. It is an error in the documentation. The build-id ARN should only have a single colon, not a double colon. I will correct this.

**Comment by dpolicastro** [comment]
Right, but why it replaces the second colon with an empty space, or simply add an empty space after a colon? Is the expected behaviour? It happens on the `source.location`, and in other fields as well.
The `time` and `build-start-time` comes like this: 
```
"time": "2020-05-08T23: 18: 10Z"
"build-start-time": "May 8, 2020 11: 17: 36 PM"
```

**Comment by dpolicastro** [comment]
About my latest comment, I made a double check here and its all good, the issue started happening after copying the event log from CloudWatch to my text editor. 

Regards, Denis

**Comment by strohm-a** [comment]
Thanks for following up.
