### ISSUE TITLE
Perplexing statement about ID format

### ISSUE THREAD

**Issue by rpcme** [awsdocs/aws-codebuild-user-guide#81]
The text says to use alphanumeric and underscores, but the example uses a hyphen.  Which is it?

> For Identifier, enter a unique file system identifier. It must be fewer than 129 characters and contain only alphanumeric characters and underscores. CodeBuild uses this identifier to create an environment variable that identifies the elastic file system. The environment variable format is CODEBUILD_file-system-identifier in capital letters. For example, if you enter efs-1, the environment variable is CODEBUILD_EFS-1.

**Comment by strohm-a** [comment]
Thanks for pointing this out. I will look into it and post an update soon.

**Comment by strohm-a** [comment]
This has been corrected.
