### ISSUE TITLE
Incorrect documentation for batch/build-graph

### ISSUE THREAD

**Issue by anderscarling** [awsdocs/aws-codebuild-user-guide#88]
It seems fc471ad19575e8ee20e1a59564df631d47a86fda introduced some issues in the documentation for `batch/build-graph` in doc_source/batch-build-buildspec.md

Basically it contains duplicated documentation for `batch/build-graph/static/env/type` and `batch/build-graph/static/env/privileged-mode`.
It also documents that `image`, `compute-type` and `variables` can be configured through `batch/build-graph/static/env` - something that does not seem to work at all.

Old version of configuration documents `image`, `compute-type` and `variables` as only configurable under `batch/build-graph/dynamic/env` - which is the only way I've managed to get the configuration to work.

**Comment by strohm-a** [comment]
Thanks. There are some errors in the documentation. 

Also, I know that the build-matrix/static/env/variables doesn't work. I now have my doubts that any of the static/env properties work and am investigating with the product team.

**Comment by anderscarling** [comment]
I know for sure `static/env/privileged-mode` works as I've used it. I can't say for sure with `static/env/type` as i've not had reason to change if from the default inherited from the project.

`static/env/image`, `static/env/compute-type` and `static/env/variables` did not work in my testing.

**Comment by strohm-a** [comment]
I removed the properties that you have noted don't work, but am still waiting to hear from the product team. I can always update the documentation if needed.
