### ISSUE TITLE
Feature request: Support for Hashicorp Terraform as a new runtime type

### ISSUE THREAD

**Issue by erikpaasonen** [awsdocs/aws-codebuild-user-guide#90]
Would like to see Terraform supported as a CodeBuild Runtime option. Should be pretty easy, it's a single executable approx. 60MB in size, and the download URL can be interpolated directly from the semver.

Current workaround is to cache the executable manually using CodeBuild buildspec commands (typically in the `Install` phase).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
