### ISSUE TITLE
Reports are failing with latest version of cucumber-js 

### ISSUE THREAD

**Issue by aurelien-reeves** [awsdocs/aws-codebuild-user-guide#91]
I don't know where to submit an issue for codebuild test reporting tools. Sorry if this is a wrong place 😨

A user of cucumber reported an issue with the latest version of cucumber-js: the codebuild report is failing with the following error message:

```
Error in UPLOAD_ARTIFACTS phase: [system: [error processing report: [/codebuild/output/src381885655/src/reports/system/cucumber.json: json: cannot unmarshal number 253118.99999999997 into Go struct field Result.elements.steps.result.duration of type time.Duration]]]
```

Indeed, in recent version of cucumber-js, the [precision of duration has been increased](https://github.com/cucumber/cucumber-js/pull/1793)

Here's the slack thread where it happened: https://cucumberbdd.slack.com/archives/C6QJ6N695/p1651483291178619

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
