### ISSUE TITLE
CodeBuild image `aws/codebuild/standard:6.0` is missing

### ISSUE THREAD

**Issue by michael-k** [awsdocs/aws-codebuild-user-guide#94]
See https://github.com/awsdocs/aws-codebuild-user-guide/blob/main/doc_source/build-env-ref-available.md (published here: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) and aws/aws-codebuild-docker-images#543

**Comment by EaganVP** [comment]
Thank you for telling us about this issue. CodeBuild image `aws/codebuild/standard:6.0` has been added.
