### ISSUE TITLE
Relevant Environment Variables not mentioned 

### ISSUE THREAD

**Issue by jatinmehrotra** [awsdocs/aws-codebuild-user-guide#98]
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

In this page, there is a list of environment variables in build environments but when I tried to use `printenv` in my build container I saw there were many other relevant environment variables which are not mentioned which could be really useful to the use in making their builds and code pipeline dynamic.

I would like to send a PR depending after discussing with team which variables ( relevant ) can be added to the list.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
